"""Run the noise-scale measurement across the settings the paper argues about.

`scripts/measure_noise_scale.py` measures one setting and prints it. This runs
the set that `results/registered-prediction-noise-scale.md` names, and writes
`results/noise-scale.md` so the prediction can be scored off a table rather than
off scrollback.

The set is chosen by that registration, not here:

  * `alpaca`, `alpaca_third`, `alpaca_ninth` at 124M -- a corpus and two random
    subsets of it, whose exponents are 1.055, 0.670 and 0.385. They share an
    example distribution exactly, so agreement between them is the validity
    check and disagreement voids the rest.
  * the same corpus at 30M and 7M, where the model changes and the noise scale
    genuinely can differ. Exploratory, and marked so.

    python scripts/run_noise_scale_series.py            # the whole set
    python scripts/run_noise_scale_series.py --repeats 8   # a faster pass
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PYTHON = REPO / ".venv" / "bin" / "python"
OUT = REPO / "results" / "noise-scale.md"

# (label, model config, checkpoint, corpus, exponent from results/exponents.csv,
#  padded supervised tokens/step, packed supervised tokens/step, of_record)
SETTINGS = [
    ("124M, Alpaca whole", "medium.yaml", "medium/step_20000.pt", "alpaca",
     1.055, 1888, 8444, True),
    ("124M, Alpaca third", "medium.yaml", "medium/step_20000.pt", "alpaca_third",
     0.670, 1841, 8296, True),
    ("124M, Alpaca ninth", "medium.yaml", "medium/step_20000.pt", "alpaca_ninth",
     0.385, 1875, 8494, True),
    ("30M, Alpaca whole", "small.yaml", "small/step_18000.pt", "alpaca",
     1.300, 1888, 8444, False),
    ("7M, Alpaca whole", "mini.yaml", "mini/step_4400.pt", "alpaca",
     1.695, 1888, 8444, False),
]

FIELDS = {
    "intercept": re.compile(r"\|G\|\^2\s+\(intercept\) = ([-\d.e+]+)"),
    "slope": re.compile(r"tr\(S\)\s+\(slope\)\s+= ([-\d.e+]+)"),
    "r2": re.compile(r"R\^2 of the fit\s+= ([-\d.]+)"),
    "b_simple": re.compile(r"B_simple = tr\(S\)/\|G\|\^2 = ([\d,]+) supervised tokens"),
}


def measure(config: str, checkpoint: str, corpus: str, repeats: int,
            packed: bool) -> dict:
    command = [
        str(PYTHON), str(REPO / "scripts" / "measure_noise_scale.py"),
        "--model", str(REPO / "configs" / "model" / config),
        "--init-from", str(REPO / "checkpoints" / checkpoint),
        "--data", str(REPO / "data" / "sft" / f"{corpus}.jsonl"),
        "--repeats", str(repeats),
    ]
    if packed:
        command.append("--packed")
    print(f"  measuring {corpus} on {config} ({'packed' if packed else 'padded'})",
          flush=True)
    result = subprocess.run(command, cwd=REPO, capture_output=True, text=True)
    if result.returncode != 0:
        print(result.stdout[-2000:], file=sys.stderr)
        print(result.stderr[-2000:], file=sys.stderr)
        raise SystemExit(f"measure_noise_scale.py failed for {corpus}/{config}")

    out = {}
    for name, pattern in FIELDS.items():
        match = pattern.search(result.stdout)
        out[name] = match.group(1).replace(",", "") if match else None
    out["raw"] = result.stdout
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--repeats", type=int, default=24)
    parser.add_argument("--packed", action="store_true",
                        help="Measure the packed dataset as well as the padded one")
    args = parser.parse_args()

    rows = []
    for label, config, checkpoint, corpus, exponent, pad_tok, pack_tok, record in SETTINGS:
        got = measure(config, checkpoint, corpus, args.repeats, packed=False)
        rows.append({"label": label, "corpus": corpus, "exponent": exponent,
                     "pad": pad_tok, "pack": pack_tok, "record": record, **got})

    lines = [
        "# Gradient noise scale, measured",
        "",
        "*Generated by `scripts/run_noise_scale_series.py`. Scored against*",
        "*`results/registered-prediction-noise-scale.md`, which was written before*",
        "*`scripts/measure_noise_scale.py` had ever been run.*",
        "",
        "`B_simple = tr(S)/|G|^2` in supervised tokens per step, so it compares",
        "directly against the padded and packed columns beside it.",
        "",
        "| setting | exponent | padded | packed | `B_simple` | packed / `B_simple` | R^2 |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for r in rows:
        b = r["b_simple"]
        ratio = f"{r['pack'] / float(b):.2f}x" if b else "—"
        lines.append(
            f"| {r['label']} | {r['exponent']:.3f} | {r['pad']:,} | {r['pack']:,} | "
            f"{int(float(b)):,} | {ratio} | {float(r['r2']):.4f} |"
            if b else
            f"| {r['label']} | {r['exponent']:.3f} | {r['pad']:,} | {r['pack']:,} | "
            f"fit failed | — | {float(r['r2']):.4f} |")

    on_record = [r for r in rows if r["record"] and r["b_simple"]]
    if len(on_record) == len(SETTINGS[:3]):
        values = [float(r["b_simple"]) for r in on_record]
        spread = max(values) / min(values)
        lines += [
            "",
            "## The validity check",
            "",
            f"The corpus and its two random subsets span **{spread:.2f}x** in `B_simple`.",
            "The registration voids everything below if that exceeds 1.5x, on the",
            "grounds that three samples of one distribution cannot have three noise",
            "scales.",
        ]

    OUT.write_text("\n".join(lines) + "\n")
    print(f"\nwrote {OUT}")
    for r in rows:
        print(f"  {r['label']:<22} B_simple {r['b_simple'] or 'fit failed':>10}  "
              f"R^2 {r['r2']}")


if __name__ == "__main__":
    main()
