"""The paper's headline numbers against the ledgers that produced them.

Every number in `paper/paper.md` was hand-checked against
`results/lr_scaling_sweep.csv` at the time it was written, and several were
wrong when first written -- an exponent quoted from a stale sweep, a loss taken
from the wrong grid point, a fraction copied from the wrong comparison. Hand
checks do not survive the next sweep landing.

So this recomputes the quantities the paper leads on, formats them exactly as the
paper formats them, and asserts the string is in the file. Bookkeeping that a
script already owns is left alone: the run count and GPU-hours are regenerated by
`scripts/update_paper_counts.py`, and a test on them would go red every time a
sweep was mid-flight without protecting anything. It is deliberately not
a parser: it does not try to find *where* the number is claimed, only that the
paper still contains the value the data supports. A sweep that moves an exponent
therefore fails here until the prose is updated, which is the point.

Cheap: reads two CSVs and solves parabolas over at most nine points each.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent.parent
PAPER = REPO / "paper" / "paper.md"
SCRIPTS = REPO / "scripts"
LEDGER = REPO / "results" / "lr_scaling_sweep.csv"

sys.path.insert(0, str(SCRIPTS))

pytestmark = pytest.mark.skipif(
    not LEDGER.exists(), reason="sweep results not present in this checkout"
)


def _series():
    """(module, rows-by-dataset) for the 124M ledger."""
    import analyze_lr_scaling as A
    import analyze_packing_series as S

    A.RESULTS = LEDGER
    return S


@pytest.fixture(scope="module")
def paper() -> str:
    return PAPER.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def exponents() -> dict[str, dict]:
    S = _series()
    out = {}
    for dataset in ("alpaca", "dolly", "alpaca_short", "alpaca_mid", "alpaca_long",
                    "alpaca_third", "alpaca_ninth", "dolly_third"):
        row = S.row(dataset, "final_val_loss")
        if row:
            out[dataset] = row
    return out


@pytest.mark.parametrize("dataset", [
    "alpaca", "dolly", "alpaca_short", "alpaca_mid", "alpaca_long",
    "alpaca_third", "alpaca_ninth", "dolly_third",
])
def test_each_exponent_the_paper_quotes_is_the_one_the_data_gives(paper, exponents, dataset):
    """Every corpus's matched-budget exponent, to three decimals as the paper writes it."""
    if dataset not in exponents:
        pytest.skip(f"{dataset} not swept in this checkout")
    value = f"{exponents[dataset]['exponent']:.3f}"
    assert value in paper, (
        f"{dataset}'s exponent is {value} in the ledger and that string is absent from "
        f"paper.md. A sweep has moved it; update the prose."
    )


def test_the_inherit_comparison_matches_the_grid(paper):
    """Section 4.4's table: the padded optimum, the same rate under packing, and retuned.

    This is the comparison that was wrong in the first draft -- it used 2e-5 where
    Alpaca's padded optimum is 3e-5 -- so it is worth pinning to the grid.
    """
    import csv

    losses = {}
    with LEDGER.open() as handle:
        for row in csv.DictReader(handle):
            if row["seed"] != "1337" or not row["final_val_loss"]:
                continue
            losses[(row["dataset"], row["cell"], float(row["max_lr"]))] = float(row["final_val_loss"])

    for dataset, padded_cell, packed_cell, rate, best in (
        ("alpaca", "unpacked_1600", "packed_350", 3e-5, 1.5e-4),
        ("dolly", "unpacked_430", "packed_136", 3e-5, 9e-5),
    ):
        for cell, lr in ((padded_cell, rate), (packed_cell, rate), (packed_cell, best)):
            value = losses.get((dataset, cell, lr))
            assert value is not None, f"missing {dataset}/{cell} at {lr:g}"
            assert f"{value:.4f}" in paper, (
                f"{dataset}/{cell} at {lr:g} is {value:.4f} in the ledger, absent from paper.md"
            )


def test_the_seed_bound_is_carried_onto_every_exponent(paper, exponents):
    """The bounds are what turned two findings into retractions; they must be current."""
    for dataset in ("alpaca", "alpaca_third", "alpaca_ninth", "dolly", "dolly_third"):
        if dataset not in exponents:
            continue
        bound = f"{exponents[dataset]['exponent_bound']:.3f}"
        assert bound in paper, (
            f"{dataset}'s seed bound is {bound} in the ledger and is absent from paper.md"
        )


def test_the_scale_comparison_still_clears_its_noise(exponents):
    """4.8 rests on this: a corpus against a third of itself, past the seed bound.

    Asserted against the data rather than the prose -- if replication ever pulls
    this below its bound, the section's central claim is gone and the paper needs
    rewriting, not a number swap.
    """
    S = _series()
    if not {"alpaca", "alpaca_third"} <= exponents.keys():
        pytest.skip("scale comparison not swept in this checkout")
    gap, bound, ratio = S.compare(exponents["alpaca_third"], exponents["alpaca"])
    assert exponents["alpaca_third"]["exponent"] < exponents["alpaca"]["exponent"], (
        "the third of Alpaca no longer sits below the whole corpus; 4.8 is wrong"
    )
    assert ratio > 1.0, (
        f"the scale gap is {gap:.3f} against a seed bound of {bound:.3f} ({ratio:.1f}x) "
        f"and no longer clears it; 4.8's central claim does not survive"
    )


def test_no_exponent_is_quoted_that_the_data_cannot_produce(exponents):
    """A sanity floor and ceiling, so a sign error or a swapped pair is caught."""
    for dataset, row in exponents.items():
        assert 0.0 < row["exponent"] < 2.0, f"{dataset} exponent {row['exponent']} is out of range"
        assert row["ratio"] > 1.0, (
            f"{dataset}: the packed optimum is not above the padded one, which would "
            f"invert the paper's central claim"
        )


# --- the other base models -------------------------------------------------
#
# The tests above cover the 124M ledger, which is where the paper's first six
# result sections live. Sections 4.7 and 4.7.1 add three more base models, and
# their exponents are quoted in the prose the same way -- so they need the same
# guard, or a re-run that moves one of them fails silently.
#
# These read results/exponents.csv rather than re-solving, because that file is
# what Appendix F and the figures are both built from: if it disagrees with the
# paper, the paper and its own table disagree, which is the failure worth
# catching. `scripts/export_exponents.py` regenerates it.

EXPONENTS_CSV = REPO / "results" / "exponents.csv"

OTHER_MODELS = [
    ("30M", "alpaca"), ("30M", "alpaca_third"), ("30M", "alpaca_ninth"),
    ("7M", "alpaca"), ("7M", "alpaca_third"),
    ("30M@19.7", "alpaca"), ("30M@19.7", "alpaca_third"),
]


@pytest.fixture(scope="module")
def exported() -> dict[tuple[str, str], dict]:
    import csv

    if not EXPONENTS_CSV.exists():
        pytest.skip("results/exponents.csv absent; run scripts/export_exponents.py")
    with EXPONENTS_CSV.open() as handle:
        return {(r["model"], r["dataset"]): r for r in csv.DictReader(handle)}


@pytest.mark.parametrize("model,dataset", OTHER_MODELS)
def test_the_paper_quotes_the_other_models_exponents_as_exported(paper, exported, model, dataset):
    """Every 30M/7M exponent, as `x.xxx ± y.yyy`, the way sections 4.7 write them."""
    row = exported.get((model, dataset))
    if row is None:
        pytest.skip(f"{model}/{dataset} not in exponents.csv")
    quoted = f"{float(row['exponent']):.3f} ± {float(row['bound']):.3f}"
    assert quoted in paper, (
        f"{model}/{dataset} is `{quoted}` in results/exponents.csv and that string is "
        f"absent from paper.md. A sweep or a re-export has moved it; update the prose "
        f"and re-run scripts/update_paper_counts.py to refresh Appendix F."
    )


def test_appendix_f_is_in_step_with_the_exported_table(paper, exported):
    """Appendix F is generated, so a stale one means the generator was not re-run."""
    for (model, dataset), row in exported.items():
        if int(row["seeds"]) < 2:
            # Provisional rows render without a bound on purpose; see
            # `exponent_table` in scripts/update_paper_counts.py.
            cell = f"**{float(row['exponent']):.3f}** (no bound)"
        else:
            cell = f"**{float(row['exponent']):.3f} ± {float(row['bound']):.3f}**"
        assert cell in paper, (
            f"Appendix F is missing {model}/{dataset} as `{cell}`. Run "
            f"`python scripts/update_paper_counts.py` to regenerate it."
        )


def test_the_exported_exponents_keep_more_digits_than_the_paper_quotes(exported):
    """Guards the rounding bug this file already caught once.

    `0.5165461` written to the CSV as `0.5165` reads back and formats to 0.516,
    while the paper -- correctly -- quotes 0.517. Any file that a printed number
    is round-tripped through has to carry more precision than the print does.
    """
    for key, row in exported.items():
        for field in ("exponent", "bound"):
            decimals = len(row[field].partition(".")[2])
            assert decimals >= 5, (
                f"{key} stores {field}={row[field]!r} with {decimals} decimals; the paper "
                f"quotes three, so the CSV needs at least five to round-trip faithfully."
            )

